version: "3.9"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HOST_ADDRESS: "http://localhost:3001/administrator"
      REDIS_HOST: "cache"
      DATABASE_HOST: "db"
    ports:
      - "3000:3001"
    command: npm run start:prod
